{% set name = "pyqtgraph" %}
{% set version = "0.10.0" %}
{% set sha256 = "4c08ab34881fae5ecf9ddfe6c1220b9e41e6d3eb1579a7d8ef501abb8e509251" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  # For the next version of pyqtgraph this patch will not be necessary anymore (greater than 0.10.0)
  patches:
    - bug-fix.patch
    - py38-fix.patch

build:
  number: 7
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    # pyqtgraph works with pyqt4 or pyqt5. Don't pin it here.
    - pyqt

test:
  imports:
    - pyqtgraph

about:
  home: http://www.pyqtgraph.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Scientific Graphics and GUI Library for Python

  description: |
    PyQtGraph is a pure-python graphics and GUI library built on PyQt4 / 
    PySide and numpy. It is intended for use in mathematics / scientific / 
    engineering applications. Despite being written entirely in python, the
    library is very fast due to its heavy leverage of numpy for number
    crunching and Qt's GraphicsView framework for fast display.
  doc_url: http://www.pyqtgraph.org/documentation/ 
  dev_url: https://github.com/pyqtgraph/pyqtgraph

extra:
  recipe-maintainers:
    - astaric
    - marcelotrevisani
