{% set name = "pyqtgraph" %}
{% set version = "0.13.5" %}
{% set sha256 = "e3b05a513da4a837055c0f8e26506f142478b2ebe9854085bf63faf84625623e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy >=1.22
  run_constrained:
    - pyside2 >=5.15
    - pyqt >=5.15

test:
  requires:
    # Add a requirement to the test phase.
    # Could be pyqt or pyside2
    - pyqt >=5.15
  imports:
    - pyqtgraph

about:
  home: http://www.pyqtgraph.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Scientific Graphics and GUI Library for Python

  description: |
    PyQtGraph is a pure-python graphics and GUI library built on PyQt / 
    PySide and numpy. It is intended for use in mathematics / scientific / 
    engineering applications. Despite being written entirely in python, the
    library is very fast due to its heavy leverage of numpy for number
    crunching and Qt's GraphicsView framework for fast display.
  doc_url: http://www.pyqtgraph.org/documentation/
  dev_url: https://github.com/pyqtgraph/pyqtgraph

extra:
  recipe-maintainers:
    - astaric
    - marcelotrevisani
    - ksunden
    - j9ac9k
