travis:
  secure:
    BINSTAR_TOKEN: gA6Ho3BnrgajNsWJ1YFB3Mr+a5jUf3J9vmRKK8mpN4v+LVk4/wUaCmTDO8+pWcVGyHm2uFRaLiP9660nrkgaFL6K5Z8L1/CkN8bGhfULkot+0f83xHWLq+Ka4YLl6log0gDeCcf3c8X+czgqCxEKco8R+3f0D6y7Claa9fBAtjIONHWi7ISrNGq10bGKt7jObAd2ydNIbOer6m9hnSbCyl23O2LJ51bE8kIK+39z1LaszLGB2zeJbqxsYbw+Cqq2Q2lIqg5OT3wW7q5mLO6OxXut3hzdFgVOrUCf2HUtJnWOQ1hId5gGkHcFeeptHtY/HOZSiyBEsmUN/WDAvSat523j86naERE35kVXVP2dqdop4nJPICMmCuD19uzcS/LnLXYJR4XvMc/wFAUuYuw6w9KkXL1OsiaVljUF0Zy8e7J6zSyIYOEyC2o6qN/LR1SqrTy/S6xoWlFA2OqxKZ2TyTmx8fNwH4EUuzTWO+8tdpqO0g0kIQlyepja5Fc3GwCwN2ccLGZYX1epG5f8JG14JJfIn2P9Ofuh1to8cE8+k+ML4MhFe05jR8t0cJerHxbSy5gyF5K2YgeViogusVysIhxtfqoD5/NNZNYZRtScIh1xvyBATwXFyIJTGP0NirQ3h9FlLIhYUSdvaciQQotqhgFXqvYbgH4f/A2D/8Q5nJM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
